
publish:
  stage: build
  image: python:latest
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: $CI_COMMIT_TAG

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.21.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor 
      --context ${CI_PROJECT_DIR} 
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile 
      --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      --destination ${CI_REGISTRY_IMAGE}:latest
  rules:
    - if: $CI_COMMIT_TAG

